// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create_user.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id,nickname,password) 
VALUES ($1,$2,$3)
RETURNING id, nickname, password
`

type CreateUserParams struct {
	ID       int32
	Nickname string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Nickname, arg.Password)
	var i User
	err := row.Scan(&i.ID, &i.Nickname, &i.Password)
	return i, err
}
