// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create_chat_user.sql

package database

import (
	"context"
)

const createUser_Chat = `-- name: CreateUser_Chat :one
INSERT INTO user_chat (
  user_id,
  chat_id
) VALUES ( $1,$2 )
RETURNING user_id, chat_id
`

type CreateUser_ChatParams struct {
	UserID int32
	ChatID int32
}

func (q *Queries) CreateUser_Chat(ctx context.Context, arg CreateUser_ChatParams) (UserChat, error) {
	row := q.db.QueryRowContext(ctx, createUser_Chat, arg.UserID, arg.ChatID)
	var i UserChat
	err := row.Scan(&i.UserID, &i.ChatID)
	return i, err
}
