// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create_user_no_id.sql

package database

import (
	"context"
)

const createUserNoId = `-- name: CreateUserNoId :one
INSERT INTO users (
  nickname,password
) VALUES ( $1,$2 )
RETURNING id, nickname, password
`

type CreateUserNoIdParams struct {
	Nickname string
	Password string
}

func (q *Queries) CreateUserNoId(ctx context.Context, arg CreateUserNoIdParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserNoId, arg.Nickname, arg.Password)
	var i User
	err := row.Scan(&i.ID, &i.Nickname, &i.Password)
	return i, err
}
