// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create_chat_one_to_one.sql

package database

import (
	"context"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats(chat_name) VALUES($1)
RETURNING id, chat_name
`

func (q *Queries) CreateChat(ctx context.Context, chatName string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat, chatName)
	var i Chat
	err := row.Scan(&i.ID, &i.ChatName)
	return i, err
}
