// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create_chat_one_to_one.sql

package database

import (
	"context"
	"database/sql"
)

const createChatOneToOne = `-- name: CreateChatOneToOne :one
INSERT INTO chats(chat_name) VALUES($1)
RETURNING id, chat_name
`

func (q *Queries) CreateChatOneToOne(ctx context.Context, chatName sql.NullString) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChatOneToOne, chatName)
	var i Chat
	err := row.Scan(&i.ID, &i.ChatName)
	return i, err
}
