// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_user_by_nickname.sql

package database

import (
	"context"
)

const getUserByNickName = `-- name: GetUserByNickName :one
SELECT id, nickname, password FROM users WHERE nickname = $1
`

func (q *Queries) GetUserByNickName(ctx context.Context, nickname string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByNickName, nickname)
	var i User
	err := row.Scan(&i.ID, &i.Nickname, &i.Password)
	return i, err
}
