// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Chat struct {
	ID       int32
	ChatName string
}

type ImageMessage struct {
	ID        int32
	MessageID sql.NullInt32
	DataUrl   sql.NullString
}

type MediaMessage struct {
	ID        int32
	MessageID sql.NullInt32
	DataUrl   sql.NullString
}

type Message struct {
	ID        int32
	ChatID    sql.NullInt32
	UserID    sql.NullInt32
	CreatedAt time.Time
}

type TextMessage struct {
	ID        int32
	MessageID sql.NullInt32
	Data      sql.NullString
}

type User struct {
	ID       int32
	Nickname string
	Password string
}

type UserChat struct {
	UserID int32
	ChatID int32
}
