// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type Chat struct {
	ID       int32
	ChatName string
}

type ImageMessage struct {
	ID        int32
	MessageID int32
	DataUrl   string
}

type MediaMessage struct {
	ID        int32
	MessageID int32
	DataUrl   string
}

type Message struct {
	ID        int32
	ChatID    int32
	UserID    int32
	CreatedAt time.Time
}

type TextMessage struct {
	ID        int32
	MessageID int32
	Data      string
}

type User struct {
	ID       int32
	Nickname string
	Password string
}

type UserChat struct {
	UserID int32
	ChatID int32
}
