-- +goose Up 
ALTER TABLE text_message ALTER COLUMN MESSAGE_ID SET NOT NULL;
ALTER TABLE text_message ALTER COLUMN DATA SET NOT NULL;
ALTER TABLE image_message ALTER COLUMN MESSAGE_ID SET NOT NULL;
ALTER TABLE image_message ALTER COLUMN DATA_URL SET NOT NULL;
ALTER TABLE media_message ALTER COLUMN MESSAGE_ID SET NOT NULL;
ALTER TABLE media_message ALTER COLUMN DATA_URL SET NOT NULL;
-- +goose Down 
ALTER TABLE media_message ALTER COLUMN MESSAGE_ID DROP NOT NULL;
ALTER TABLE media_message ALTER COLUMN DATA_URL DROP NOT NULL;
ALTER TABLE text_message ALTER COLUMN MESSAGE_ID DROP NOT NULL;
ALTER TABLE text_message ALTER COLUMN DATA DROP NOT NULL;
ALTER TABLE image_message ALTER COLUMN MESSAGE_ID DROP NOT NULL;
ALTER TABLE image_message ALTER COLUMN DATA_URL DROP NOT NULL;
